spring:
  flyway.baseline-on-migrate: true
  datasource:
    # IDEA cannot connect to an in-memory db, so we store it in a file
    # also, cannot use relative path due to https://youtrack.jetbrains.com/issue/IDEA-252118
    url: jdbc:h2:file:~/db;AUTO_SERVER=TRUE
    username: 'sa'
    password: ''
  security:
    # we aren't using OAuth2 nor any resource server
    # but we're reusing the existing Spring code for just the JWT support
    oauth2.resourceserver.jwt.public-key-location: classpath:dev/rsa_public.pem

jwt:
  private-key: classpath:dev/rsa_private.pem
  valid-for: 1h

logging.level:
  root: info
  com.toptal.screening.soccerplayermarket: trace
  org.springframework.security.web.access.ExceptionTranslationFilter: debug
  org.hibernate.SQL: debug
  org.hibernate.type.descriptor: trace
  org.hibernate.tool.hbm2ddl: debug
  org.hibernate.cache: debug
