spring:
  profiles.active: prod
  application.name: base-app
  flyway.baseline-version: 0.1.0
  hazelcast.config: classpath:hazelcast.xml
  jpa:
    open-in-view: false
    hibernate.ddl-auto: validate
    properties:
      #only entities with @Cacheable annotation will use cache.
      javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
      hibernate:
        cache:
          use_second_level_cache: true
          # only queries containing hibernate hint will be cached
          use_query_cache: true
          hazelcast.configuration_file_path: ${spring.hazelcast.config}
          region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory

jwt.valid-for: 1m

springdoc:
  writer-with-order-by-keys: true
  api-docs:
    enabled: false
    path: /open-api/v3/api-docs
  swagger-ui:
    path: /open-api/swagger-ui.html
  paths-to-match: /api/**
  # ErrorResponse gets removed with this enabled
  remove-broken-reference-definitions: false